/**
 * The block, in a browser.
 *
 * The PHPUnit suite already proves the render callback wraps its content the
 * way the shortcode wraps its content, so repeating that here would buy
 * nothing. What only a browser can answer is whether the *built* JavaScript
 * works: `build/` is generated by bin/build and is not in the repository, so
 * every assertion below is also an assertion that the build ran and produced
 * something a browser can load.
 *
 * Three things are worth a browser, and nothing else here is:
 *
 * * the editor script loads and registers the block -- a broken build, a
 *   missing dependency in index.asset.php or a bad block.json all show up here
 *   and nowhere else;
 * * the content inside the block is edited as ordinary blocks, which is the
 *   whole reason this block holds inner blocks rather than previewing a
 *   shortcode;
 * * a toggle that arrived through the block actually toggles. The script is
 *   enqueued by whatever rendered the toggle, so a block that forgot to enqueue
 *   it renders markup that looks perfect and a button that does nothing. That
 *   is the failure this file exists for.
 */

const { test, expect } = require( '@wordpress/e2e-test-utils-playwright' );

/** The block this plugin registers. */
const BLOCK = 'wp-showhide/showhide';

/**
 * Post content holding the block, with one paragraph inside it.
 *
 * Written out rather than round-tripped through the editor, because this is
 * exactly what the editor saves and a published post is what the front-end
 * tests are about.
 *
 * @param {string} body       The paragraph inside the block.
 * @param {string} attributes JSON attributes for the block comment, if any.
 * @return {string} Serialised block markup.
 */
function blockContent( body, attributes = '' ) {
	return (
		`<!-- wp:${ BLOCK }${ attributes ? ' ' + attributes : '' } -->\n` +
		`<!-- wp:paragraph --><p>${ body }</p><!-- /wp:paragraph -->\n` +
		`<!-- /wp:${ BLOCK } -->`
	);
}

/**
 * Publish a post with the given content, and open it.
 *
 * @param {Object}                          requestUtils The e2e request helper.
 * @param {import('@playwright/test').Page} page         Page under test.
 * @param {string}                          content      Post content.
 * @return {Promise<Object>} The created post.
 */
async function openPost( requestUtils, page, content ) {
	const post = await requestUtils.createPost( {
		title: `Show hide block ${ Date.now().toString( 36 ) }`,
		content,
		status: 'publish',
	} );

	await page.goto( post.link );

	return post;
}

test.describe( 'The showhide block', () => {
	test.describe( 'in the editor', () => {
		test( 'is registered, under the prefixed name', async ( {
			admin,
			editor,
			page,
		} ) => {
			await admin.createNewPost();
			await editor.canvas.locator( 'body' ).waitFor();

			const names = await page.evaluate( () =>
				window.wp.blocks.getBlockTypes().map( ( type ) => type.name ),
			);

			// If the build did not run, or index.asset.php named a dependency
			// that does not exist, the editor script never executes and the
			// name is not here -- which is the failure this whole file exists
			// for.
			expect( names ).toContain( BLOCK );

			// The prefix is not decoration: a block name is written into
			// post_content and lives there for the life of the post.
			expect( names ).not.toContain( 'showhide/showhide' );
		} );

		test( 'holds its content as ordinary blocks', async ( {
			admin,
			editor,
		} ) => {
			await admin.createNewPost();
			await editor.insertBlock( {
				name: BLOCK,
				innerBlocks: [
					{
						name: 'core/paragraph',
						attributes: { content: 'Editable inner paragraph' },
					},
				],
			} );

			// Visible and editable in the canvas, not folded into a preview and
			// not typed into a textarea as raw markup. The enclosing shortcode
			// is the reason: what it wraps is the writer's content, so the
			// editor has to be able to edit it.
			const paragraph = editor.canvas.locator(
				'p:has-text("Editable inner paragraph")',
			);

			await expect( paragraph ).toBeVisible();
			await expect( paragraph ).toHaveAttribute( 'contenteditable', 'true' );

			// And it is really the inner block of ours, rather than a paragraph
			// that landed beside it.
			const saved = await editor.getEditedPostContent();

			expect( saved ).toContain( `<!-- wp:${ BLOCK } -->` );
			expect( saved ).toContain( 'Editable inner paragraph' );
		} );
	} );

	test.describe( 'on the front end', () => {
		test( 'a toggle that came from a block actually toggles', async ( {
			page,
			requestUtils,
		} ) => {
			await openPost(
				requestUtils,
				page,
				blockContent( 'The quick brown fox jumps over the lazy dog.' ),
			);

			const toggle = page.locator( '.sh-toggle' );
			const content = page.locator( '.sh-content' );

			await expect( toggle ).toBeVisible();
			await expect( toggle ).toHaveAttribute( 'aria-expanded', 'false' );
			await expect( content ).toBeHidden();

			// The click is the point. Everything above it is markup the PHP
			// suite has already seen; this needs the script, and the script is
			// enqueued by the render callback -- so a block that did not
			// enqueue it fails here and passes everywhere else.
			await toggle.click();

			await expect( toggle ).toHaveAttribute( 'aria-expanded', 'true' );
			await expect( content ).toBeVisible();
			await expect( content ).toContainText( 'quick brown fox' );

			await toggle.click();

			await expect( toggle ).toHaveAttribute( 'aria-expanded', 'false' );
			await expect( content ).toBeHidden();
		} );

		test( 'the script is on a page whose only toggle is a block', async ( {
			page,
			requestUtils,
		} ) => {
			const plain = await requestUtils.createPost( {
				title: `No toggle ${ Date.now().toString( 36 ) }`,
				content: 'Nothing to toggle here.',
				status: 'publish',
			} );

			await page.goto( plain.link );

			await expect(
				page.locator( 'script[src*="js/wp-showhide.js"]' ),
			).toHaveCount( 0 );

			await openPost( requestUtils, page, blockContent( 'Body' ) );

			// The same asymmetry the shortcode has: only the pages that render
			// a toggle pay for the script.
			await expect(
				page.locator( 'script[src*="js/wp-showhide.js"]' ),
			).toHaveCount( 1 );
		} );

		test( 'the block counts the words it is hiding', async ( {
			page,
			requestUtils,
		} ) => {
			// Nine words, and they arrive as rendered inner blocks rather than
			// as the raw text between two shortcode tags -- so this is also the
			// check that the callback is counting the content it was handed.
			await openPost(
				requestUtils,
				page,
				blockContent( 'The quick brown fox jumps over the lazy dog' ),
			);

			await expect( page.locator( '.sh-toggle' ) ).toHaveText(
				'Show Press Release (9 More Words)',
			);
		} );

		test( 'attributes saved in the block comment are honoured', async ( {
			page,
			requestUtils,
		} ) => {
			await openPost(
				requestUtils,
				page,
				blockContent( 'The ending', '{"type":"spoiler","hidden":false}' ),
			);

			await expect( page.locator( '.spoiler-link' ) ).toHaveCount( 1 );
			await expect( page.locator( '.sh-toggle' ) ).toHaveAttribute(
				'aria-expanded',
				'true',
			);
			await expect( page.locator( '.sh-content' ) ).toBeVisible();
		} );

		test( 'a block and a shortcode on one page work independently', async ( {
			page,
			requestUtils,
		} ) => {
			// The block is an addition, so the two have to coexist in one post:
			// distinct ids, and one button opening one block.
			await openPost(
				requestUtils,
				page,
				blockContent( 'From the block' ) +
					'\n\n[showhide]From the shortcode[/showhide]',
			);

			const toggles = page.locator( '.sh-toggle' );
			const contents = page.locator( '.sh-content' );

			await expect( toggles ).toHaveCount( 2 );

			const ids = await contents.evaluateAll( ( nodes ) =>
				nodes.map( ( node ) => node.id ),
			);
			expect( new Set( ids ).size ).toBe( 2 );

			await toggles.first().click();

			await expect( contents.first() ).toBeVisible();
			await expect( contents.last() ).toBeHidden();

			await toggles.last().click();

			await expect( contents.last() ).toBeVisible();
		} );
	} );
} );
